### ISSUE TITLE
Error while starting Discord Bot

### ISSUE THREAD

**Issue by Underlyingglitch** [Exiled-Team/DiscordIntegration#50]
This is the error I'm seeing. I checked my configuration twice:

```
[steam@localhost dcbot2]$ node discordIntegration.js
/home/steam/dcbot2/discordIntegration.js:183
        console.error(`[NET][ERROR] An error has occurred while receiving data from ${socket?.address()?.address}:${socket?.address()?.port}: ${exception}`);
                                                                                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[steam@localhost dcbot2]$
```

**Comment by iopietro** [comment]
Update Node.js.
