### ISSUE TITLE
DiscordIntegration doen't recognize voice channel chats

### ISSUE THREAD

**Issue by EvaProject-Netzach** [Exiled-Team/DiscordIntegration#87]
**Describe the bug**
Discord has a new option for voicechat channels, now you can use voice channels as a temporally chat channel, but the bot doesn't recognize that channel as a text channel, it gets buggy and disconect from the main server.

**To Reproduce**
1. Go to 'Discord'
2. Click on 'Voicechat, open text chat and write something while the server and the bot is opened.'
3. Goto bot console.

**Server logs**
[DISCORD][WARN] Discord sent a typing packet to a voice channel 960280391749603370
C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\actions\MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^

TypeError: Cannot read properties of undefined (reading 'cache')
    at MessageCreateAction.handle (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\actions\MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:526:28)
    at Receiver.receiverOnMessage (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\ws\lib\websocket.js:1047:20)
    at Receiver.emit (node:events:526:28)
    at Receiver.dataMessage (C:\Users\Usuario\Desktop\DiscordIntegration.Bot\node_modules\ws\lib\receiver.js:517:14)
    
**EXILED Version ("latest" is not a version):** 
5.1.3

**Additional context**
To trigger the bug you have to open the server and the bot as normally, then you have to connect to a voicechat on discord and use the "create channel" and write a message.

**Comment by xRoier** [comment]
The bot is not intended to be used like that, Joker will most probably just close this issue.

**Comment by joker-119** [comment]
What he said. My coming rewrite of the bot *may* be able to use VC Chats but it won't be a planned feature, nor will it be supported in any way.
