### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fluffy41** [Exiled-Team/DiscordIntegration#89]
so when i wanted to start the Bot this happend (Config is okay and i used the latest version)

js discordIntegration.js 
/home/scpsl/discordbot1/discordIntegration.js:186
        console.error(`[NET][ERROR] An error has occurred while receiving data from ${socket?.address()?.address}:${socket?.address()?.port}: ${exception}`);
                                                                                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3

**Comment by joker-119** [comment]
Not a bug, run npm install as shown in the install instructions.
